\mainmatter

# Bookdown 介绍及安装 {#intro}

[Bookdown](https://bookdown.org/) 是一个面向科研人员的文档写作、转换、发布工具，基于 R markdown、git、gitbook、pandoc、tex等开源工具，尤其适合于爱折腾的同学。使用 bookdown 写作的在线开源书籍有：

1. [bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)
1. [R 语言教程](http://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/index.html)

## 为什么用 bookdown

相对于 Word、Tex、Gitbook、Vuepress 等工具而言，bookdown 具有如下优势：

1. 编译速度快。
1. 完美支持数学公式的显示。
1. 内置对 R markdown 的支持，能够运行R代码，并直接将运行结果显示在文档中。
1. 对学术写作支持更好，如参考文献、交叉引用等等。
1. 开源，且由科研人员群体开发和维护，了解科研人员需求。

但bookdown也存在学习成本较高的问题，估计大多数科研人员不会投入时间去了解。我碰巧有tex、gitbook的使用经验，所以在用bookdown时能够较快地掌握，但即便如此，我也花费了近2天时间，才算基本掌握。

## 使用 bookdown 的准备工作

### 安装 R

到[R的官方网站](https://www.r-project.org/)，下载适合系统的最新包，尤其是 Mac 系统，还需要安装官方网站提到的 XQuartz 。

### 安装 Rstudio

到官网下载 [R studio](https://rstudio.com/)，安装到合适路径，路径名不要使用中文。

另外，RStudio 自带 Pandoc 相关工具，无需单独安装。

RStudio 的使用可参考如下文档：<https://resources.rstudio.com/rstudio-developed/rstudio-ide>。

### 安装 bookdown 

启动 RStudio，设置到最近的镜像（非必须，只是为了加快下载速度），然后安装 bookdown，在控制台中运行：

```R
install.packages("bookdown")
```

安装完成后，重启 RStudio。

### 安装 tex

此步骤非必须，仅在生成 PDF 时需要。建议安装 [tex live](https://tug.org/texlive/) 官方版本，而非其他简化版。

### 下载适合中文的模板

Bookdown 的作者[谢益辉博士](https://yihui.org/)，提供了适合非常[不错的中文排版模板](https://github.com/yihui/bookdown-chinese)。使用 RStudio 打开后，即可在其基础上专心于进行内容的创作。

北京大学的[李东风教授](http://www.math.pku.edu.cn/teachers/lidf/)，也提供了一个[非常实用的中文模板](http://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/index.html)。
